server:
  port: 8888
spring:
  application:
    name: isb-cloud-config
  profiles:
    active: subversion
  cloud:     
    config:
      enabled: true
      server:
        svn:
          uri: http://x.x.x.x:3690/svn/xxx/
          username: username
          password: pwd
        default-label: trunk

  